# NumPy Exercises

**1. Array Creation**
- Create an array of zeros with size 5.
- Create an array of integers from 10 to 20.
- Create an array of random integers between 0 and 100 with size (3, 3).

**2. Indexing and Slicing**
- Given the array `arr = np.array([1, 2, 3, 4, 5])`, access the third element.
- Create a 2D array of shape (4, 4) and access the entire second row.
- Given an array `arr = np.arange(25).reshape(5, 5)`, extract the subarray containing the first two rows and the first three columns.

**3. Mathematical Operations**
- Create two arrays of size 5 and perform element-wise addition and multiplication between them.
- Multiply all elements of an array by 10.
- Create an array of integers and calculate the mean, sum, and maximum value.

**4. Reshaping**
- Create an array of numbers from 1 to 16 and reshape it into a 4x4 array.
- Transpose the previous array (swap rows and columns).
- From a 3D array with shape (2, 3, 3), flatten it into a 2D array.

**5. Broadcasting**
- Create a (3, 3) size integer array and add 10 to each element of the array without using loops.
- Multiply a 1D array of size 3 by a 2D array of size (3, 3).

**6. Masks and Conditions**
- Create a random integer array of size (5, 5) and use a mask to replace all values less than 10 with 0.
- Given the array `arr = np.array([10, 5, 8, 12, 6, 2])`, create a mask to select only the values greater than 6.

**7. Concatenation and Division**
- Create two arrays of shape (2, 3). Concatenate them along axis 0 (rows) and axis 1 (columns).
- Divide an array of 10 elements into 2 arrays of equal size.

**8. NumPy Specific Functions**
- Create an array of integers from 0 to 9 and calculate the sine of each number.
- Create an array of values from 1 to 100 and find the indices of the values that are divisible by 5.


In [24]:
# Question 1
import numpy

# - Create an array of zeros with size 5.
arr = numpy.zeros(5, dtype=int) # By default the zeros function generate a matrix by float
print(arr)

# - Create an array of integers from 10 to 20.
arr = numpy.arange(10, 21)
print(arr)

# - Create an array of random integers between 0 and 100 with size (3, 3).
arr = numpy.random.randint(0, 101, size=(3, 3))
print(arr)

# Another way
# import random

# arr = numpy.zeros([3, 3], dtype=int)
# row, col = arr.shape

# for i in range(row):
#     for j in range(col):
#         r = random.randint(0, 100)
#         arr[i][j] = r

# print(arr)

[0 0 0 0 0]
[10 11 12 13 14 15 16 17 18 19 20]
[[62 48 90]
 [12 39 12]
 [89  6 93]]
