# NumPy Exercises

**1. Array Creation**
- Create an array of zeros with size 5.
- Create an array of integers from 10 to 20.
- Create an array of random integers between 0 and 100 with size (3, 3).

**2. Indexing and Slicing**
- Given the array `arr = np.array([1, 2, 3, 4, 5])`, access the third element.
- Create a 2D array of shape (4, 4) and access the entire second row.
- Given an array `arr = np.arange(25).reshape(5, 5)`, extract the subarray containing the first two rows and the first three columns.

**3. Mathematical Operations**
- Create two arrays of size 5 and perform element-wise addition and multiplication between them.
- Multiply all elements of an array by 10.
- Create an array of integers and calculate the mean, sum, and maximum value.

**4. Reshaping**
- Create an array of numbers from 1 to 16 and reshape it into a 4x4 array.
- Transpose the previous array (swap rows and columns).
- From a 3D array with shape (2, 3, 3), flatten it into a 2D array.

**5. Broadcasting**
- Create a (3, 3) size integer array and add 10 to each element of the array without using loops.
- Multiply a 1D array of size 3 by a 2D array of size (3, 3).

**6. Masks and Conditions**
- Create a random integer array of size (5, 5) and use a mask to replace all values less than 10 with 0.
- Given the array `arr = np.array([10, 5, 8, 12, 6, 2])`, create a mask to select only the values greater than 6.

**7. Concatenation and Division**
- Create two arrays of shape (2, 3). Concatenate them along axis 0 (rows) and axis 1 (columns).
- Divide an array of 10 elements into 2 arrays of equal size.

**8. NumPy Specific Functions**
- Create an array of integers from 0 to 9 and calculate the sine of each number.
- Create an array of values from 1 to 100 and find the indices of the values that are divisible by 5.


In [1]:
# Question 1
import numpy

# - Create an array of zeros with size 5.
arr = numpy.zeros(5, dtype=int) # By default the zeros function generate a matrix by float
print(arr)

# - Create an array of integers from 10 to 20.
arr = numpy.arange(10, 21)
print(arr)

# - Create an array of random integers between 0 and 100 with size (3, 3).
arr = numpy.random.randint(0, 101, size=(3, 3))
print(arr)

# Another way
# import random

# arr = numpy.zeros([3, 3], dtype=int)
# row, col = arr.shape

# for i in range(row):
#     for j in range(col):
#         r = random.randint(0, 100)
#         arr[i][j] = r

# print(arr)

[0 0 0 0 0]
[10 11 12 13 14 15 16 17 18 19 20]
[[40  5 77]
 [66 18 53]
 [31 35 31]]


In [2]:
# Question 2

# - Given the array `arr = np.array([1, 2, 3, 4, 5])`, access the third element.
arr = numpy.array([1, 2, 3, 4, 5])
print(arr[2])

# - Create a 2D array of shape (4, 4) and access the entire second row.
arr = numpy.arange(16).reshape(4, 4)
print(arr[1])

# - Given an array `arr = np.arange(25).reshape(5, 5)`, extract the subarray containing the first two rows and the first three columns.
arr = numpy.arange(25).reshape(5, 5)
sub_arr = arr[:2, :3]
print(sub_arr)

3
[4 5 6 7]
[[0 1 2]
 [5 6 7]]


In [3]:
# Question 3

# - Create two arrays of size 5 and perform element-wise addition and multiplication between them.
arr_1 = numpy.arange(5)
arr_2 = numpy.arange(5)
print(f"The addition equal: {arr_1 + arr_2}")
print(f"The multiplication equal: {arr_1 * arr_2}")

# - Multiply all elements of an array by 10.
arr = numpy.array([[1, 2, 3], [9, 6, 2]])
print(arr * 10)

# - Create an array of integers and calculate the mean, sum, and maximum value.
arr = numpy.arange(9)
print(numpy.mean(arr))
print(arr.sum())
print(arr.max())

The addition equal: [0 2 4 6 8]
The multiplication equal: [ 0  1  4  9 16]
[[10 20 30]
 [90 60 20]]
4.0
36
8


In [4]:
# Question 4

# - Create an array of numbers from 1 to 16 and reshape it into a 4x4 array.
arr = numpy.arange(1, 17).reshape(4, 4)
print(arr)

# - Transpose the previous array (swap rows and columns).
print(arr.T)

# - From a 3D array with shape (2, 3, 3), flatten it into a 2D array.
arr = numpy.zeros((2, 3, 3), dtype=int)  # Forma correta: (2, 3, 3)
flattened_arr_2d = arr.flatten().reshape(9, 2)
print(flattened_arr_2d)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
[[ 1  5  9 13]
 [ 2  6 10 14]
 [ 3  7 11 15]
 [ 4  8 12 16]]
[[0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]]


In [15]:
# Question 5

# - Create a (3, 3) size integer array and add 10 to each element of the array without using loops.
arr = numpy.array([ [4, 9, 12], [20, 24, 15], [55, 67, 42]])
arr += 10
print(arr)

# - Multiply a 1D array of size 3 by a 2D array of size (3, 3).
arr_1d = numpy.arange(3)
arr_2d = numpy.arange(9).reshape(3, 3)
arr_mul = arr_1d * arr_2d
print(arr_mul)

[[14 19 22]
 [30 34 25]
 [65 77 52]]
[0 1 2]
[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 0  1  4]
 [ 0  4 10]
 [ 0  7 16]]
